services:
  - type: web
    name: kspdb-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: serve -s dist -l 3000
    envVars:
      - key: VITE_API_URL
        value: https://kspdb-backend.onrender.com
